name: Daily Calendar Digest

on:
  schedule:
    # Run at 6 AM UTC (7 AM GMT+1 for Europe/Lagos)
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv pip install .[dev]
        
    - name: Run tests
      run: |
        uv run pytest tests/ -v
        
    - name: Run Orbit Digest
      env:
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        TIMEZONE: ${{ secrets.TIMEZONE || 'Europe/Berlin' }}
        DIGEST_HOUR: ${{ secrets.DIGEST_HOUR || '7' }}
        QUIET_HOURS_START: ${{ secrets.QUIET_HOURS_START || '22' }}
        QUIET_HOURS_END: ${{ secrets.QUIET_HOURS_END || '7' }}
      run: |
        uv run python -m src.main
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: orbit-digest-logs
        path: logs/
        retention-days: 7 